#!/bin/sh

upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
secs=$((${upSeconds}%60))
mins=$((${upSeconds}/60%60))
hours=$((${upSeconds}/3600%24))
days=$((${upSeconds}/86400))
UPTIME=`printf "%d days, %02dh%02dm%02ds" "$days" "$hours" "$mins" "$secs"`

echo "$(tput setaf 4)
`date +"%A, %e %B %Y, %r"`
`uname -srmo`

    \/      
_\_\/\/_/_  Uptime.............: ${UPTIME}
 _\_\/_/_   Memory.............: `awk '/MemFree/ {printf( "%d\n", $2 / 1024 )}' /proc/meminfo`MB (Free) / `awk '/MemTotal/ {printf( "%d\n", $2 / 1024 )}' /proc/meminfo`MB (Total)
__/_/\_\__  CPU Temperature....: `/opt/vc/bin/vcgencmd measure_temp | cut -c 6-`
 / /\/\ \   IP Addresses.......: `ip a | grep glo | awk '{print $2}' | head -1 | cut -f1 -d/`
    /\      
$(tput sgr0)"


 



