version: "3"
services:
    matomo:
        image: matomo:latest
        environment:
            - "MATOMO_DATABASE_HOST=db"
            - "MATOMO_DATABASE_ADAPTER=mysql"
            - "MATOMO_DATABASE_USERNAME=matomo"
            - "MATOMO_DATABASE_PASSWORD=${MYSQL_MATOMO_PASSWORD}"
            - "MATOMO_DATABASE_DBNAME=matomo"
        volumes:
            - ${PERSISTENT_DIR}/matomo/data:/var/www/html
        depends_on:
            - db
        networks:
            - web
            - internal
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.analytics.entrypoints=https"
            - "traefik.http.routers.analytics.rule=Host(`analytics.${DOMAIN_BASE}`)"
            - "traefik.http.routers.analytics.tls=true"
            - "traefik.http.routers.analytics.tls.certresolver=letsencrypt"
            - "traefik.http.routers.analytics.tls.domains[0].main=analytics.${DOMAIN_BASE}"
            - "traefik.http.services.analytics.loadbalancer.server.port=80"
            - "com.centurylinklabs.watchtower.enable=true"
        restart: unless-stopped
    
    db:
        image: mariadb:10.5
        container_name: matomo_db
        volumes:
            - ${PERSISTENT_DIR}/matomo/db:/var/lib/mysql
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - MYSQL_USER=matomo
            - MYSQL_DATABASE=matomo
            - MYSQL_PASSWORD=${MYSQL_MATOMO_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
        networks:
            - internal
        restart: unless-stopped


networks:
    internal:
    web:
        external: true
